sonar.projectKey=felipecorinthiano011_studyflow-saas
sonar.organization=felipecorinthiano011

# Sources
sonar.sources=backend/src/main/java
sonar.tests=backend/src/test/java
sonar.test.inclusions=**/*Test.java,**/*Tests.java

# Exclusions
sonar.exclusions=**/config/**,**/entity/**

# Java
sonar.java.source=21
sonar.java.binaries=backend/target/classes

# Coverage
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
sonar.coverage.exclusions=**/config/**,**/entity/**,**/dto/**

# Code Analysis
sonar.qualitygate.wait=true

